baseURL = "https://dgitek.github.io/nerdblog/"
languageCode = "en-us"
title = "[DGI]tech's Technical Tales"
theme = "m10c"

[params]
  author = "[DGI]tech"
  description = "Future Tech Author"
  avatar = "static/avatar.jpg"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/DGItek"